import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { ThemeProvider } from "@/components/theme-provider";
import QueryProvider from "@/lib/queryProvider";
const inter = Inter({ subsets: ["latin"] });
import { Sync } from "@/components/Sync";
import Navbar from "@/components/Navbar";
import { cn } from "@/lib/utils";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head />
      <QueryProvider>
        <body
          className={cn(
            "flex flex-col overflow-x-hidden m-0 p-0",
            inter.className
          )}
          suppressHydrationWarning={true}
        >
          <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
            <Navbar></Navbar>
            {children}
            {/* <Sync></Sync> */}
          </ThemeProvider>
        </body>
      </QueryProvider>
    </html>
  );
}
